name: stage

on: [push, pull_request, workflow_dispatch]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Configure SSH
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          PORT: ${{ secrets.PORT }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $HOST
            User $USERNAME
            Port $PORT
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Generate
        env:
          BASE_URL: https://johannagroiss.wolfgangdrescher.ch
          DEPLOY_ENV: stage
        run: npm run generate --universal

      - name: Remove files
        run: ssh staging "rm -rf johannagroiss.wolfgangdrescher.ch/*"

      - name: Deploy
        run: rsync -azP dist/ staging:johannagroiss.wolfgangdrescher.ch
